GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTk4MjI0ODUsImV4cCI6MTYyMDA4MTY4NSwiYXVkIjoiNjA4YzUyN2NjMDg0MWJkODJjODQyNzhjIn0.W8ONls2Y4mBbdPWChk6e02z18mzIooLGhVRJ_bbpCNc

####register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "user": {
        "email":"briankib@gmail.com",
        "password":"helloworld",
        "firstName":"123",
        "lastName":"kiba"
    }
}

####login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "user": {
        "email":"briankib@gmail.com",
        "password":"helloworld",
        "firstName":"123",
        "lastName":"kiba"
    }
}

####refresh
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "refreshToken":
     "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjAxMzk2MjQsImV4cCI6MTY1MTY5NzIyNCwiYXVkIjoiNjA4YzUyN2NjMDg0MWJkODJjODQyNzhjIn0.qAsqBrDIeQWAHmBeq57InGdBNq70uaZAek0m6gPDyT8"
}

####logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken":
     "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjAxMzk2MjQsImV4cCI6MTY1MTY5NzIyNCwiYXVkIjoiNjA4YzUyN2NjMDg0MWJkODJjODQyNzhjIn0.qAsqBrDIeQWAHmBeq57InGdBNq70uaZAek0m6gPDyT8"
}
